package bloodbankms;

import javax.management.StringValueExp;

public class GUI_DonateBlood extends javax.swing.JFrame{
    
    User userDonor = new Donor("piya", "aloha", "Sofhia", "F", 66, 45.1f, "B+", null, 2, 1, 12);
    User userPatient = new Patient(null, null, null, null, 0, 0, null, null);
                
    //downCasting
    Donor obj = (Donor) userDonor;
    Patient patient = (Patient) userPatient;

    public GUI_DonateBlood(){
        initComponents();}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        btnConfirm = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        NameLbl = new javax.swing.JLabel();
        GenderLbl = new javax.swing.JLabel();
        AgeLbl = new javax.swing.JLabel();
        WeightLbl = new javax.swing.JLabel();
        cmbGender = new javax.swing.JComboBox<>();
        txtAge = new javax.swing.JTextField();
        txtWeight = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        BloodGLbl = new javax.swing.JLabel();
        cmbBloodGroup = new javax.swing.JComboBox<>();
        WeightLbl1 = new javax.swing.JLabel();
        WeightLbl2 = new javax.swing.JLabel();
        WeightLbl3 = new javax.swing.JLabel();
        txtWeek = new javax.swing.JTextField();
        radHealthyYes = new javax.swing.JRadioButton();
        radHealthyNo = new javax.swing.JRadioButton();
        radPvtYes = new javax.swing.JRadioButton();
        radPvtNo = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        CompatibilityTxt = new javax.swing.JLabel();
        RecipientTxt = new javax.swing.JLabel();
        RBFTxt = new javax.swing.JLabel();
        BloodGroupTxt = new javax.swing.JLabel();
        BloodCompTxt = new javax.swing.JLabel();
        labelDonor = new javax.swing.JLabel();
        labelBlood = new javax.swing.JLabel();
        labelDonateTo = new javax.swing.JLabel();
        labelWeight = new javax.swing.JLabel();
        labelEligibility = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(204, 255, 255));
        jLabel1.setFont(new java.awt.Font("Lucida Bright", 1, 36)); // NOI18N
        jLabel1.setText("Donate Blood");

        btnConfirm.setBackground(new java.awt.Color(204, 255, 255));
        btnConfirm.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnConfirm.setText("Confirm");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Donor Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Bright", 1, 18), new java.awt.Color(0, 51, 255))); // NOI18N
        jPanel1.setToolTipText("");

        NameLbl.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        NameLbl.setText("Name     ");

        GenderLbl.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        GenderLbl.setText("Gender  ");

        AgeLbl.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        AgeLbl.setText("Age        ");

        WeightLbl.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        WeightLbl.setText("Weight   ");

        cmbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Sex>", "Male", "Female" }));
        cmbGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbGenderActionPerformed(evt);
            }
        });

        txtAge.setToolTipText("");
        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });

        txtWeight.setToolTipText("");
        txtWeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWeightActionPerformed(evt);
            }
        });

        btnSubmit.setBackground(new java.awt.Color(204, 255, 255));
        btnSubmit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        txtName.setToolTipText("");
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        BloodGLbl.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        BloodGLbl.setText("Blood Group");

        cmbBloodGroup.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Blood>", "A+", "O+", "B+", "AB+", "A-", "O-", "AB-" }));
        cmbBloodGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBloodGroupActionPerformed(evt);
            }
        });

        WeightLbl1.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        WeightLbl1.setText("Healthy?");

        WeightLbl2.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        WeightLbl2.setText("Private name?");

        WeightLbl3.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        WeightLbl3.setText("Last donation week");

        txtWeek.setToolTipText("");
        txtWeek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWeekActionPerformed(evt);
            }
        });

        buttonGroup1.add(radHealthyYes);
        radHealthyYes.setText("Yes");

        buttonGroup1.add(radHealthyNo);
        radHealthyNo.setText("No");

        buttonGroup2.add(radPvtYes);
        radPvtYes.setText("Yes");

        buttonGroup2.add(radPvtNo);
        radPvtNo.setText("No");
        radPvtNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radPvtNoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(GenderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AgeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(76, 76, 76)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(WeightLbl3)
                                                .addGap(17, 17, 17)
                                                .addComponent(txtWeek, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(WeightLbl2)
                                                .addGap(18, 18, 18)
                                                .addComponent(radPvtYes, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cmbGender, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(68, 68, 68)
                                        .addComponent(WeightLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(radHealthyYes, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(WeightLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(17, 17, 17))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(BloodGLbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbBloodGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radHealthyNo, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radPvtNo, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtName)
                        .addGap(3, 3, 3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(NameLbl)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(radHealthyYes)
                                .addComponent(radHealthyNo))
                            .addComponent(WeightLbl1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GenderLbl)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cmbGender)
                        .addGap(2, 2, 2)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AgeLbl)
                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtWeight)
                            .addComponent(WeightLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BloodGLbl)
                            .addComponent(cmbBloodGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(WeightLbl2)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(radPvtYes)
                                .addComponent(radPvtNo)))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtWeek)
                            .addComponent(WeightLbl3))))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Eligibility Preview", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Bright", 1, 18), new java.awt.Color(0, 153, 153))); // NOI18N

        CompatibilityTxt.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N

        RecipientTxt.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N

        RBFTxt.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N

        BloodGroupTxt.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N

        BloodCompTxt.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N

        labelDonor.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        labelDonor.setText("Donor:");

        labelBlood.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        labelBlood.setText("Blood Group:");

        labelDonateTo.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        labelDonateTo.setText("Donate Blood To:");

        labelWeight.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        labelWeight.setText("Weight:");

        labelEligibility.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        labelEligibility.setText("Eligibility:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelWeight)
                            .addComponent(labelDonateTo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RBFTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BloodCompTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(labelDonor)
                        .addGap(18, 18, 18)
                        .addComponent(RecipientTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(labelBlood)
                        .addGap(18, 18, 18)
                        .addComponent(BloodGroupTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(labelEligibility)
                        .addGap(18, 18, 18)
                        .addComponent(CompatibilityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(293, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDonor)
                    .addComponent(RecipientTxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBlood)
                    .addComponent(BloodGroupTxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDonateTo)
                    .addComponent(RBFTxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelWeight)
                    .addComponent(BloodCompTxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEligibility)
                    .addComponent(CompatibilityTxt))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(230, 230, 230))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(271, 271, 271))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(29, 29, 29)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbBloodGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBloodGroupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbBloodGroupActionPerformed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        
        GUI_Menu guiBack = new GUI_Menu();
        guiBack.show();
        dispose();
        
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void cmbGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbGenderActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        
        obj.setName(txtName.getText()); //Get Name from textfield
        obj.setAge(Integer.parseInt(txtAge.getText())); //Get Age from textfield
        obj.setWeight(Integer.parseInt(txtWeight.getText())); //Get Weight from textfield
        obj.setLastWeekDonation(Integer.parseInt(txtWeek.getText())); //Get Week Donation from textfield
        
        //Get Gender from option box
        if(cmbGender.getSelectedIndex()==1)
            obj.setGender("Male");
        else if(cmbGender.getSelectedIndex()==2)
            obj.setGender("Female");
        
        //Get Blood type from option box
        if(cmbBloodGroup.getSelectedIndex()==1)
            obj.setBloodGroup("A+");
        else if(cmbBloodGroup.getSelectedIndex()==2)
            obj.setBloodGroup("O+");
        else if(cmbBloodGroup.getSelectedIndex()==3)
            obj.setBloodGroup("B+");
        else if(cmbBloodGroup.getSelectedIndex()==4)
            obj.setBloodGroup("AB+");
        else if(cmbBloodGroup.getSelectedIndex()==5)
            obj.setBloodGroup("A-");
        else if(cmbBloodGroup.getSelectedIndex()==6)
            obj.setBloodGroup("O-");
        else if(cmbBloodGroup.getSelectedIndex()==7)
            obj.setBloodGroup("AB-");
        
        //Get health status and anonymity
        if(radHealthyYes.isSelected()){
            obj.setHealthStatus(1);}
        else if(radHealthyNo.isSelected()){
            obj.setHealthStatus(2);}
        else if(radPvtYes.isSelected()){
            obj.setAnonymity(1);}
        else if(radPvtNo.isSelected()){
            obj.setAnonymity(2);}
        
        //Output
        labelDonor.setText("Donor                   : " +obj.getName());
        labelBlood.setText("Blood Group         : " +obj.getBloodGroup());
        labelDonateTo.setText("Donate Blood To  : " +obj.checkRecipient());
        labelWeight.setText("Weight                  : " +String.valueOf(obj.getWeight()));
        labelEligibility.setText("Eligibility             : " +obj.checkEligibilty()); 
        
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void txtWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWeightActionPerformed

    private void txtWeekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWeekActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWeekActionPerformed

    private void radPvtNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radPvtNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radPvtNoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_DonateBlood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_DonateBlood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_DonateBlood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_DonateBlood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_DonateBlood().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AgeLbl;
    private javax.swing.JLabel BloodCompTxt;
    private javax.swing.JLabel BloodGLbl;
    private javax.swing.JLabel BloodGroupTxt;
    private javax.swing.JLabel CompatibilityTxt;
    private javax.swing.JLabel GenderLbl;
    private javax.swing.JLabel NameLbl;
    private javax.swing.JLabel RBFTxt;
    private javax.swing.JLabel RecipientTxt;
    private javax.swing.JLabel WeightLbl;
    private javax.swing.JLabel WeightLbl1;
    private javax.swing.JLabel WeightLbl2;
    private javax.swing.JLabel WeightLbl3;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnSubmit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cmbBloodGroup;
    private javax.swing.JComboBox<String> cmbGender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelBlood;
    private javax.swing.JLabel labelDonateTo;
    private javax.swing.JLabel labelDonor;
    private javax.swing.JLabel labelEligibility;
    private javax.swing.JLabel labelWeight;
    private javax.swing.JRadioButton radHealthyNo;
    private javax.swing.JRadioButton radHealthyYes;
    private javax.swing.JRadioButton radPvtNo;
    private javax.swing.JRadioButton radPvtYes;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtWeek;
    private javax.swing.JTextField txtWeight;
    // End of variables declaration//GEN-END:variables
}
