package bloodbankms;

public class GUI_DisplayBlood extends javax.swing.JFrame{
    
    Hospital hospital1 = new Hospital("Selangor", "Kajang Hospital               ", "Public ", new BloodBank());
    Hospital hospital2 = new Hospital("Selangor", "Ampang Hospital               ", "Public ", new BloodBank());
    Hospital hospital3 = new Hospital("Selangor", "KPJ Kajang Specialist Hospital", "Private", new BloodBank());
    Hospital hospital4 = new Hospital("Johor   ", "Sultanah Aminah Hospital      ", "Public ", new BloodBank());
    Hospital hospital5 = new Hospital("Johor   ", "Columbia Asia Hospital        ", "Private", new BloodBank());
    Hospital hospital6 = new Hospital("Penang  ", "Island Hospital               ", "Private", new BloodBank());
    
    public GUI_DisplayBlood(){
        initComponents();}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelDisplayBlood = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        labelHospital = new javax.swing.JLabel();
        btnDisplay = new javax.swing.JButton();
        btnReturn = new javax.swing.JButton();
        labelHospital3 = new javax.swing.JLabel();
        labelHospital1 = new javax.swing.JLabel();
        labelHospital2 = new javax.swing.JLabel();
        labelHospital6 = new javax.swing.JLabel();
        labelHospital4 = new javax.swing.JLabel();
        labelHospital5 = new javax.swing.JLabel();
        txtHospital = new javax.swing.JTextField();
        labelBloodGroup = new javax.swing.JLabel();
        inputBloodGroup = new javax.swing.JLabel();
        txtBloodGroup = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        lblHospital = new javax.swing.JLabel();
        lblDonor = new javax.swing.JLabel();
        inputHospitalNo1 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelDisplayBlood.setBackground(new java.awt.Color(204, 255, 255));
        labelDisplayBlood.setFont(new java.awt.Font("Lucida Bright", 1, 36)); // NOI18N
        labelDisplayBlood.setText("Display Blood");

        labelHospital.setText("LIST OF HOSPITAL             STATE            SECTOR");

        btnDisplay.setText("Display");
        btnDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayActionPerformed(evt);
            }
        });

        btnReturn.setText("Return");
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });

        labelHospital3.setText("...");

        labelHospital1.setText("...");

        labelHospital2.setText("...");

        labelHospital6.setText("...");

        labelHospital4.setText("...");

        labelHospital5.setText("...");

        labelBloodGroup.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        labelBloodGroup.setText("Blood Group: [A+/ O+/ B+/ AB+/ A-/ O-/ B-/ AB-]");

        inputBloodGroup.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        inputBloodGroup.setText("Search blood group: ");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "List of Donors", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Bright", 1, 18), new java.awt.Color(0, 153, 153))); // NOI18N

        lblHospital.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        lblHospital.setText("Hospital:");

        lblDonor.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        lblDonor.setText("1)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblHospital, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDonor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(421, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHospital, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDonor, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        inputHospitalNo1.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        inputHospitalNo1.setText("Search hospital no: ");

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelHospital5, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelHospital4, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelHospital6, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelHospital2, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelHospital1, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelHospital3, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelHospital, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(68, 68, 68))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(labelDisplayBlood))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(279, 279, 279)
                        .addComponent(btnDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(btnReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelBloodGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(inputHospitalNo1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtHospital, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(inputBloodGroup)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtBloodGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelDisplayBlood)
                .addGap(9, 9, 9)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDisplay)
                    .addComponent(btnReturn))
                .addGap(18, 18, 18)
                .addComponent(labelHospital, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelHospital1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(labelHospital2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelHospital3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelHospital4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelHospital5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelHospital6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHospital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputHospitalNo1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelBloodGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBloodGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputBloodGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayActionPerformed
        
        //Output
        labelHospital1.setText("1. " +hospital1.getName() +" " +hospital1.getState() +" " +hospital1.getSector());
        labelHospital2.setText("2. " +hospital2.getName() +" " +hospital2.getState() +" " +hospital2.getSector());
        labelHospital3.setText("3. " +hospital3.getName() +" " +hospital3.getState() +" " +hospital3.getSector());
        labelHospital4.setText("4. " +hospital4.getName() +" " +hospital4.getState() +" " +hospital4.getSector());
        labelHospital5.setText("5. " +hospital5.getName() +" " +hospital5.getState() +" " +hospital5.getSector());
        labelHospital6.setText("6. " +hospital6.getName() +" " +hospital6.getState() +" " +hospital6.getSector());

    }//GEN-LAST:event_btnDisplayActionPerformed

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        
        GUI_Menu guiBack = new GUI_Menu();
        guiBack.show();
        dispose();
    }//GEN-LAST:event_btnReturnActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        
        User donor1 = new Donor("mary", "stethometer", "Maria", "F", 98, 24.1f, "A+", hospital1, 2, 1, 12);
        User donor2 = new Donor("izz", "windbound", "Izzani", "M", 84, 68.1f, "O+", hospital1, 2, 1, 12);
        User donor3 = new Donor("shaz", "materteral", "Shazlien Chin", "F", 67, 45.1f, "B+", hospital1, 2, 1, 12);
        User donor4 = new Donor("carr", "muciferous", "Carrie Siu", "F", 76, 75.1f, "AB+", hospital1, 2, 1, 12);
        User donor5 = new Donor("letchum", "vespertilian", "Mahaletchumy", "F", 66, 45.1f, "A-", hospital1, 2, 1, 12);
        User donor6 = new Donor("tehah", "ontography", "Nurfatehah Lee", "F", 67, 45.1f, "O-", hospital1, 2, 1, 12);
        User donor7 = new Donor("hender", "killock", "Henderson", "M", 47, 45.1f, "B-", hospital1, 2, 1, 12);
        User donor8 = new Donor("teresa", "hypolimnion", "Teresa Koay", "F", 76, 45.1f, "AB-", hospital1, 2, 1, 12);
        
        if(txtHospital.getText().equals("1")){
            lblHospital.setText("Hospital: " +hospital1.getName());}
        else if(txtHospital.getText().equals("2")){
            lblHospital.setText("Hospital: " +hospital2.getName());}
        else if(txtHospital.getText().equals("3")){
            lblHospital.setText("Hospital: " +hospital3.getName());}
        else if(txtHospital.getText().equals("4")){
            lblHospital.setText("Hospital: " +hospital4.getName());}
        else if(txtHospital.getText().equals("5")){
            lblHospital.setText("Hospital: " +hospital5.getName());}
        else if(txtHospital.getText().equals("6")){
            lblHospital.setText("Hospital: " +hospital6.getName());}
        else{
            lblHospital.setText("Hospital: No hospital found!");}
        
        if(txtBloodGroup.getText().equals("A+")){
            lblDonor.setText("1) " +donor1.getName());}
        else if(txtBloodGroup.getText().equals("O+")){
            lblDonor.setText("1) " +donor2.getName());}
        else if(txtBloodGroup.getText().equals("B+")){
            lblDonor.setText("1) " +donor3.getName());}
        else if(txtBloodGroup.getText().equals("AB+")){
            lblDonor.setText("1) " +donor4.getName());}
        else if(txtBloodGroup.getText().equals("A-")){
            lblDonor.setText("1) " +donor5.getName());}
        else if(txtBloodGroup.getText().equals("O-")){
            lblDonor.setText("1) " +donor6.getName());}
        else if(txtBloodGroup.getText().equals("B-")){
            lblDonor.setText("1) " +donor7.getName());}
        else if(txtBloodGroup.getText().equals("AB-")){
            lblDonor.setText("1) " +donor8.getName());}
        
    }//GEN-LAST:event_btnSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_DisplayBlood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_DisplayBlood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_DisplayBlood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_DisplayBlood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_DisplayBlood().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDisplay;
    private javax.swing.JButton btnReturn;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel inputBloodGroup;
    private javax.swing.JLabel inputHospitalNo1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelBloodGroup;
    private javax.swing.JLabel labelDisplayBlood;
    private javax.swing.JLabel labelHospital;
    private javax.swing.JLabel labelHospital1;
    private javax.swing.JLabel labelHospital2;
    private javax.swing.JLabel labelHospital3;
    private javax.swing.JLabel labelHospital4;
    private javax.swing.JLabel labelHospital5;
    private javax.swing.JLabel labelHospital6;
    private javax.swing.JLabel lblDonor;
    private javax.swing.JLabel lblHospital;
    private javax.swing.JTextField txtBloodGroup;
    private javax.swing.JTextField txtHospital;
    // End of variables declaration//GEN-END:variables
}
