/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bloodbankms;

/**
 *
 * @author Azham Helmi
 */
public class PatientGUI extends javax.swing.JFrame {
    
    User obj = new Patient();  // Creating Object
    Patient ob = (Patient) obj;
    
    // --------------------------------------------------------------------------
    
    User user[] = new User[14];
        
        //Parent class reference to child object
//        user[0] = new Patient("lisa", "sasa", "Malisa", "F", 21, 44.2f, "A+", hospital[0]);
//        user[1] = new Donor("piya", "aloha", "Sofhia", "F", 66, 45.1f, "B+", hospital[0], 2, 1, 12);
//        user[2] = new Donor("mary", "stethometer", "Maria", "F", 98, 24.1f, "A+", hospital[0], 2, 1, 12);
//        user[3] = new Donor("shaz", "materteral", "Shazlien Chin", "F", 67, 45.1f, "B+", hospital[0], 2, 1, 12);
//        user[4] = new Donor("carr", "muciferous", "Carrie Siu", "F", 76, 75.1f, "AB+", hospital[0], 2, 1, 12);
//        user[5] = new Donor("izz", "windbound", "Izzani", "M", 84, 68.1f, "O+", hospital[0], 2, 1, 12);
//        user[6] = new Donor("letchum", "vespertilian", "Mahaletchumy", "F", 66, 45.1f, "A-", hospital[0], 2, 1, 12);
//        user[7] = new Donor("jane", "hygiology", "Janet", "F", 34, 45.1f, "O-", hospital[0], 2, 1, 12);
//        user[8] = new Donor("hender", "killock", "Henderson", "M", 47, 45.1f, "B-", hospital[0], 2, 1, 12);
//        user[9] = new Donor("teresa", "hypolimnion", "Teresa Koay", "F", 76, 45.1f, "AB-", hospital[0], 2, 1, 12);
//        user[10] = new Donor("lyssa", "obelisk", "Alyssa Norzamri", "F", 54, 45.1f, "B+", hospital[0], 2, 1, 12);
//        user[11] = new Donor("pijah", "roodge", "Hafezah Loi", "F", 47, 45.1f, "B+", hospital[0], 2, 1, 12);
//        user[12] = new Donor("rach", "pultaceous", "Rachel Zizi", "F", 49, 45.1f, "O+", hospital[0], 2, 1, 12);
//        user[13] = new Donor("tehah", "ontography", "Nurfatehah Lee", "F", 67, 45.1f, "O-", hospital[0], 2, 1, 12);
        
        //downCasting
        Patient userPatient = (Patient) user[0];
        Donor userDonor = (Donor) user[1];
    
    
    
    // --------------------------------------------------------------------------
    
    /**
     * Creates new form PatientGUI
     */
    public PatientGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ConfirmButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        NameLbl = new javax.swing.JLabel();
        GenderLbl = new javax.swing.JLabel();
        AgeLbl = new javax.swing.JLabel();
        WeightLbl = new javax.swing.JLabel();
        GenderBox = new javax.swing.JComboBox<>();
        TextAge = new javax.swing.JTextField();
        TextWeight = new javax.swing.JTextField();
        SubmitButton = new javax.swing.JButton();
        TextName = new javax.swing.JTextField();
        BloodGLbl = new javax.swing.JLabel();
        BloodGroupBox = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        CompatibilityTxt = new javax.swing.JLabel();
        RecipientTxt = new javax.swing.JLabel();
        RBFTxt = new javax.swing.JLabel();
        BloodGroupTxt = new javax.swing.JLabel();
        BloodCompTxt = new javax.swing.JLabel();
        RecipientTxt1 = new javax.swing.JLabel();
        BloodGroupTxt1 = new javax.swing.JLabel();
        RBFTxt1 = new javax.swing.JLabel();
        BloodCompTxt1 = new javax.swing.JLabel();
        CompatibilityTxt1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(204, 255, 255));
        jLabel1.setFont(new java.awt.Font("Lucida Bright", 1, 36)); // NOI18N
        jLabel1.setText("Receive Blood");

        ConfirmButton.setBackground(new java.awt.Color(204, 255, 255));
        ConfirmButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ConfirmButton.setText("Confirm");
        ConfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmButtonActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Patient Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Bright", 1, 18), new java.awt.Color(0, 51, 255))); // NOI18N
        jPanel1.setToolTipText("");

        NameLbl.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        NameLbl.setText("Name     ");

        GenderLbl.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        GenderLbl.setText("Gender  ");

        AgeLbl.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        AgeLbl.setText("Age        ");

        WeightLbl.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        WeightLbl.setText("Weight   ");

        GenderBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Select>", "Male", "Female" }));
        GenderBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenderBoxActionPerformed(evt);
            }
        });

        TextAge.setToolTipText("");
        TextAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextAgeActionPerformed(evt);
            }
        });

        TextWeight.setToolTipText("");
        TextWeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextWeightActionPerformed(evt);
            }
        });

        SubmitButton.setBackground(new java.awt.Color(204, 255, 255));
        SubmitButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SubmitButton.setText("Submit");
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });

        TextName.setToolTipText("");
        TextName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextNameActionPerformed(evt);
            }
        });

        BloodGLbl.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        BloodGLbl.setText("Blood Group");

        BloodGroupBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Select>", "A+", "O+", "B+", "AB+", "A-", "O-", "AB-" }));
        BloodGroupBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BloodGroupBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GenderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AgeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TextName, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(GenderBox, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(78, 78, 78))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(TextAge, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(WeightLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(BloodGLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BloodGroupBox, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(SubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(TextName)
                        .addGap(3, 3, 3))
                    .addComponent(NameLbl))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GenderLbl)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(GenderBox)
                        .addGap(2, 2, 2)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AgeLbl)
                    .addComponent(TextAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TextWeight)
                    .addComponent(WeightLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BloodGLbl)
                    .addComponent(BloodGroupBox, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Compability Preview", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Bright", 1, 18), new java.awt.Color(0, 153, 153))); // NOI18N

        CompatibilityTxt.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N

        RecipientTxt.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N

        RBFTxt.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N

        BloodGroupTxt.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N

        BloodCompTxt.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N

        RecipientTxt1.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        RecipientTxt1.setText("Recipient:");

        BloodGroupTxt1.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        BloodGroupTxt1.setText("Blood Group:");

        RBFTxt1.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        RBFTxt1.setText("Receive Blood From:");

        BloodCompTxt1.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        BloodCompTxt1.setText("Blood Compatibility:");

        CompatibilityTxt1.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        CompatibilityTxt1.setText("Compatibility:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BloodCompTxt1)
                            .addComponent(RBFTxt1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RBFTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BloodCompTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(RecipientTxt1)
                        .addGap(18, 18, 18)
                        .addComponent(RecipientTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(BloodGroupTxt1)
                        .addGap(18, 18, 18)
                        .addComponent(BloodGroupTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(CompatibilityTxt1)
                        .addGap(18, 18, 18)
                        .addComponent(CompatibilityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(262, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RecipientTxt1)
                    .addComponent(RecipientTxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BloodGroupTxt1)
                    .addComponent(BloodGroupTxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RBFTxt1)
                    .addComponent(RBFTxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BloodCompTxt1)
                    .addComponent(BloodCompTxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CompatibilityTxt1)
                    .addComponent(CompatibilityTxt))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ConfirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(230, 230, 230))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(271, 271, 271))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(29, 29, 29)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(ConfirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BloodGroupBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BloodGroupBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BloodGroupBoxActionPerformed

    private void ConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConfirmButtonActionPerformed

    private void GenderBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenderBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GenderBoxActionPerformed

    private void TextNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextNameActionPerformed

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        obj.setName(TextName.getText()); //  Get Name from textfield
        int a = Integer.parseInt(TextAge.getText()); //  Get Age from textfield
        int w = Integer.parseInt(TextWeight.getText()); //  Get Weight from textfield
        
        //  Get Gender from option box
        if(GenderBox.getSelectedIndex()==1)
            obj.setGender("Male");
        else if(GenderBox.getSelectedIndex()==2)
            obj.setGender("Female");
        
        //  Get Blood type from option box
        if(BloodGroupBox.getSelectedIndex()==1)
            obj.setBloodGroup("A+");
        else if(BloodGroupBox.getSelectedIndex()==2)
            obj.setBloodGroup("O+");
        else if(BloodGroupBox.getSelectedIndex()==3)
            obj.setBloodGroup("B+");
        else if(BloodGroupBox.getSelectedIndex()==4)
            obj.setBloodGroup("AB+");
        else if(BloodGroupBox.getSelectedIndex()==5)
            obj.setBloodGroup("A-");
        else if(BloodGroupBox.getSelectedIndex()==6)
            obj.setBloodGroup("O-");
        else if(BloodGroupBox.getSelectedIndex()==7)
            obj.setBloodGroup("AB-");
        
        //  Outputs
        RecipientTxt.setText(obj.getName());
        BloodGroupTxt.setText(obj.getBloodGroup());
        RBFTxt.setText("Someone");  // UNKNOWN 
        BloodCompTxt.setText(ob.getBloodMatch());  // UNKNOWN 
        CompatibilityTxt.setText(ob.checkCompatibility(ob.bloodGroup)); // UNKNOWN 
        
        
        
        
    }//GEN-LAST:event_SubmitButtonActionPerformed

    private void TextAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextAgeActionPerformed

    private void TextWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextWeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextWeightActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AgeLbl;
    private javax.swing.JLabel BloodCompTxt;
    private javax.swing.JLabel BloodCompTxt1;
    private javax.swing.JLabel BloodGLbl;
    private javax.swing.JComboBox<String> BloodGroupBox;
    private javax.swing.JLabel BloodGroupTxt;
    private javax.swing.JLabel BloodGroupTxt1;
    private javax.swing.JLabel CompatibilityTxt;
    private javax.swing.JLabel CompatibilityTxt1;
    private javax.swing.JButton ConfirmButton;
    private javax.swing.JComboBox<String> GenderBox;
    private javax.swing.JLabel GenderLbl;
    private javax.swing.JLabel NameLbl;
    private javax.swing.JLabel RBFTxt;
    private javax.swing.JLabel RBFTxt1;
    private javax.swing.JLabel RecipientTxt;
    private javax.swing.JLabel RecipientTxt1;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JTextField TextAge;
    private javax.swing.JTextField TextName;
    private javax.swing.JTextField TextWeight;
    private javax.swing.JLabel WeightLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
